### ISSUE TITLE
Adds recipes for 10 Thermal Expansion ingots to nothing in the Induction Smelter

### ISSUE THREAD

**Issue by aaronhowser1** [Tomson124/SimplyJetpacks2#28]
![](https://cdn.discordapp.com/attachments/434101214548852746/797371539313524746/unknown.png)

I found out what mod was causing this after over an hour of binary searching

This is using `SimplyJetpacks2-1.16.3-2.6.3.0`, and the config is:

```toml
	[simplyjetpacks-common.integration]
		#Enable EnderIO Jetpacks Integration.
		enableIntegrationEnderIO = false
		#Enable Thermal Expansion Jetpacks Integration.
		enableIntegrationThermalExpansion = true
		#Enable Thermal Dynamics Jetpacks Integration.
		enableIntegrationThermalDynamics = true
		#Enable Mekanism Jetpacks Integration.
		enableIntegrationMekanism = true
		#Enable Vanilla Jetpacks Integration.
		enableIntegrationVanilla = true
		#Enable Immersive Engineering Jetpacks Integration.
		enableIntegrationImmersiveEngineering = true

```
